# Generated by Django 5.0.4 on 2024-12-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdropapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(help_text='Main heading with dynamic content')),
                ('highlight_text', models.CharField(help_text='Highlighted text in the heading', max_length=255)),
                ('subheading', models.TextField(help_text='Subheading or description')),
                ('safe_water_solutions', models.CharField(default='10K+', max_length=50)),
                ('customer_support', models.CharField(default='24/7', max_length=50)),
                ('after_service_guarantee', models.CharField(default='100%', max_length=50)),
                ('image', models.ImageField(help_text='Upload the image for the right section', upload_to='about_section/')),
            ],
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='section_content/')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.CharField(max_length=255)),
                ('request_quote_url', models.URLField(default='#')),
                ('whatsapp_url', models.URLField(default='https://wa.me/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_content/')),
            ],
        ),
    ]
