# Generated by Django 5.0.4 on 2024-12-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdropapp', '0002_aboutsection_sectioncontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Enter the expertise title (e.g., 'Commercial Water Treatment')", max_length=255)),
                ('description_1', models.TextField(blank=True, help_text='Enter the first description point')),
                ('description_2', models.TextField(blank=True, help_text='Enter the second description point')),
                ('description_3', models.TextField(blank=True, help_text='Enter the third description point')),
                ('image', models.ImageField(help_text='Upload an image for the card', upload_to='expertise/')),
            ],
        ),
    ]
