# Generated by Django 5.0.4 on 2024-12-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdropapp', '0003_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text="Enter the heading (e.g., 'UV Water Purifier')", max_length=255)),
                ('description', models.TextField(help_text='Enter the description of the water solution')),
                ('image', models.ImageField(help_text='Upload an image for the water solution', upload_to='water_solutions/')),
                ('button_text', models.CharField(default='Download Catalog', help_text='Button text for catalog', max_length=255)),
                ('button_link', models.URLField(blank=True, help_text='Enter the URL for the catalog download')),
            ],
        ),
    ]
