# Generated by Django 5.0.4 on 2024-12-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdropapp', '0005_filtrationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Name of the client', max_length=255)),
                ('client_image', models.ImageField(help_text="Client's image", upload_to='testimonials/')),
                ('title', models.CharField(help_text='Title or brief summary of the testimonial', max_length=255)),
                ('message', models.TextField(help_text='Full testimonial message')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating out of 5')),
            ],
        ),
    ]
