# Generated by Django 5.0.4 on 2024-12-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdropapp', '0007_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload the product image', upload_to='product_showcase/')),
                ('alt_text', models.CharField(help_text='Alt text for the image', max_length=255)),
            ],
        ),
    ]
