# Generated by Django 5.0.4 on 2024-12-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdropapp', '0008_productshowcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterTreatmentProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Step number (e.g., 1, 2, 3, etc.)', unique=True)),
                ('heading', models.CharField(help_text='Heading for the step', max_length=255)),
                ('points', models.TextField(help_text='Enter each point separated by a semicolon (;)')),
            ],
        ),
    ]
