# Generated by Django 5.0.4 on 2024-12-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdropapp', '0009_watertreatmentprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watersolution',
            name='description',
        ),
        migrations.RemoveField(
            model_name='watersolution',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='watersolution',
            name='image',
        ),
        migrations.AddField(
            model_name='watersolution',
            name='ro_description',
            field=models.TextField(blank=True, help_text='Description for RO Water Purifier', null=True),
        ),
        migrations.AddField(
            model_name='watersolution',
            name='ro_heading',
            field=models.CharField(default='Default RO Heading', help_text='Heading for RO Water Purifier', max_length=255),
        ),
        migrations.AddField(
            model_name='watersolution',
            name='ro_image',
            field=models.ImageField(blank=True, default='Default RO Heading', help_text='Image for RO Water Purifier', null=True, upload_to='water_solutions/'),
        ),
        migrations.AddField(
            model_name='watersolution',
            name='uv_description',
            field=models.TextField(blank=True, default='Default RO Heading', help_text='Description for UV Water Purifier', null=True),
        ),
        migrations.AddField(
            model_name='watersolution',
            name='uv_heading',
            field=models.CharField(default='Default RO Heading', help_text='Heading for UV Water Purifier', max_length=255),
        ),
        migrations.AddField(
            model_name='watersolution',
            name='uv_image',
            field=models.ImageField(blank=True, help_text='Image for UV Water Purifier', null=True, upload_to='water_solutions/'),
        ),
        migrations.AlterField(
            model_name='watersolution',
            name='button_link',
            field=models.URLField(blank=True, default='Default RO Heading', help_text='Enter the URL for catalog download', null=True),
        ),
    ]
